

POST http://localhost:3333/usuarios
Content-type: application/json

{
  "nome": "João da Silva",
  "email": "joaodasilva@gmail.com",
  "celular": "44 91234-1234"
}

###

POST http://localhost:3333/usuarios
Content-type: application/json

{
  "nome": "Maria Freitas",
  "email": "mariafreitas@gmail.com",
  "celular": "44 94321-4321"
}

###

GET http://localhost:3333/usuarios

###

GET http://localhost:3333/usuarios?nome=joão

###

PUT http://localhost:3333/usuarios/b8093df3-d630-429c-acb4-36b6ee74c560
Content-type: application/json
Accept-Language: pt

{
  "nome": "João da Silva",
  "email": "joaodasilva2@gmail.com",
  "celular": "44 91234-1234"
}

###

DELETE http://localhost:3333/usuarios/b8093df3-d630-429c-acb4-36b6ee74c560
